# 1. --- Builder Stage ---
# Use Node.js 20 (as specified in your project)
FROM node:20-alpine AS builder
WORKDIR /app

# Install build-time dependencies
RUN apk add --no-cache libc6-compat openssl

# Copy package files and install all dependencies
COPY package.json package-lock.json* ./
RUN npm install --production=false

# Copy the rest of the source code
COPY . .

# --- ADD THIS LINE ---
# Provide a dummy value for the build process
ENV DATABASE_URL="postgres://dummy:dummy@dummy/dummy"
# ---------------------

# Build the Next.js standalone application
# This uses your build script
RUN npm run build

# 2. --- Runner Stage ---
FROM node:20-alpine AS runner
WORKDIR /app

# Set production environment
ENV NODE_ENV=production

# Copy standalone output from the builder
COPY --from=builder /app/.next/standalone ./
# Copy static assets
COPY --from=builder /app/.next/static ./.next/static
# Copy instrumentation file (needed for your MQTT listener)
COPY --from=builder /app/instrumentation.ts ./instrumentation.ts

# Expose port 3000
EXPOSE 3000

# Start the Node.js server (this server.js is generated by Next.js)
CMD ["node", "server.js"]